python src/parse.py --input tests/test_1.java --verbose 
python src/parse.py --input tests/test_2.java --verbose
python src/parse.py --input tests/test_3.java --verbose
python src/parse.py --input tests/test_4.java --verbose
python src/parse.py --input tests/test_5.java --verbose
python src/parse.py --input tests/test_6.java --verbose
python src/parse.py --input tests/test_7.java --verbose
python src/parse.py --input tests/test_8.java --verbose
python src/parse.py --input tests/test_9.java --verbose
python src/parse.py --input tests/test_10.java --verbose